platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

def shared_pods
    pod 'Masonry'
end

target 'SFCustomButton' do
    shared_pods
end

#新scheme在pods里Debug模式无效解决方案：http://stackoverflow.com/questions/21046282/debug-preprocessor-macro-not-defined-for-cocoapods-targets
post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] ='9.0'
            if config.name != 'Release'
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'DEBUG=1']
                config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-DDEBUG']
            end
        end
    end
end



